services:
  - type: web
    name: quiz-master-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gevent -b 0.0.0.0:10000 app:app"
    envVars:
      - key: SECRET_KEY
        value: quiz_master_secure_key_2025
